const activities=[
 {id:1,title:'瑗垮哺鑹烘湳瀛?路 澶滃満',tag:'鑹烘湳 路 瀹ゅ唴澶?,price:60,distance:'2.1km',time:'浠婂ぉ 18:30',people:'杩樺樊 2 浜?,interest:'鑹烘湳',outdoor:false,cls:'card-1',reason:'鏅村ぉ鍌嶆櫄锛岄€傚悎鎱㈡參閫?},
 {id:2,title:'澶у璺懆鏈垱鎰忓競闆?,tag:'甯傞泦 路 閫涘悆',price:0,distance:'1.4km',time:'浠婂ぉ 14:00',people:'宸叉湁 3 浜?,interest:'甯傞泦',outdoor:true,cls:'card-2',reason:'鍏嶈垂涓旂浣犲緢杩?},
 {id:3,title:'灞嬮《鐖靛＋ 路 鏃ヨ惤鍦?,tag:'闊充箰 路 鐜板満',price:128,distance:'3.2km',time:'浠婂ぉ 19:30',people:'杩樺樊 1 浜?,interest:'闊充箰',outdoor:true,cls:'card-3',reason:'鏅存湕澶╂皵鐨勯檺瀹氭氮婕?},
 {id:4,title:'浣樺北杞诲緬姝?路 妫灄绾?,tag:'鑷劧 路 寰掓',price:45,distance:'28km',time:'鏄庡ぉ 08:00',people:'宸叉湁 5 浜?,interest:'鑷劧',outdoor:true,cls:'card-4',reason:'浣撳姏鍒氬ソ锛岄鏅濂?}
];
let selected='all', weather='sunny', saved=JSON.parse(localStorage.getItem('weekend-saved')||'[]'), checked=JSON.parse(localStorage.getItem('weekend-checkins')||'[]');
const $=s=>document.querySelector(s), list=$('#activityList');
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function render(){const budget=+$('#budget').value;let items=activities.filter(a=>(selected==='all'||a.interest===selected)&&a.price<=budget);if(weather==='rainy')items.sort((a,b)=>(a.outdoor?1:0)-(b.outdoor?1:0));$('#resultCount').textContent=items.length;list.innerHTML=items.length?items.map(a=>`<article class="card ${a.cls}"><button class="save ${saved.includes(a.id)?'saved':''}" data-save="${a.id}" aria-label="鏀惰棌 ${a.title}">${saved.includes(a.id)?'鈾?:'鈾?}</button><span class="pill">${a.tag}</span><h3>${a.title}</h3><div class="meta"><span>楼${a.price||'鍏嶈垂'}</span><span>${a.distance}</span><span>${a.time}</span></div><p class="match">鉁?${weather==='rainy'&&a.outdoor?'闆ㄥぉ澶囬€夛紝寤鸿甯︿紴':a.reason}</p><div class="card-actions"><button class="detail" data-detail="${a.id}">鏌ョ湅璇︽儏</button><button class="join" data-join="${a.id}">缁勯槦 路 ${a.people}</button></div></article>`).join(''):`<div class="empty">娌℃湁瀹屽叏绗﹀悎鐨勬椿鍔ㄣ€傝瘯璇曟斁瀹介绠楁垨鍒囨崲鍏磋叮銆?/div>`;$('#savedCount').textContent=saved.length;$('#checkinCount').textContent=checked.length;$('#checkinCopy').textContent=checked.length?`杩欎釜鍛ㄦ湯宸茬偣浜?${checked.length} 涓柊鍦扮偣锛岀户缁繚鎸併€俙:'浠庝竴涓皬灏忕殑鍛ㄦ湯璁″垝寮€濮嬨€?}
document.addEventListener('click',e=>{const id=+(e.target.dataset.save||e.target.dataset.detail||e.target.dataset.join||0), a=activities.find(x=>x.id===id);if(e.target.dataset.save){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('weekend-saved',JSON.stringify(saved));render();toast(saved.includes(id)?'宸插姞鍏ヤ綘鐨勫懆鏈竻鍗?:'宸蹭粠娓呭崟绉婚櫎')}if(e.target.dataset.detail&&a){$('#detailContent').innerHTML=`<div class="detail-art ${a.cls}"></div><p class="eyebrow">${a.tag}</p><h2>${a.title}</h2><p class="detail-line">${a.time} 路 璺濈 ${a.distance} 路 ${a.price?'楼'+a.price:'鍏嶈垂'}<br>闆嗗悎鍚庤嚜鐢辨帰绱紝閫傚悎 ${$('#people').selectedOptions[0].textContent} 鍑哄彂銆?/p><div class="detail-buttons"><button class="primary" data-check="${id}">${checked.includes(id)?'宸插畬鎴愭墦鍗?:'鍒板満鍚庢墦鍗?}</button><button class="primary" data-share="${id}">鍒嗕韩鏀荤暐</button></div>`;$('#detailDialog').showModal()}if(e.target.dataset.join&&a){toast(`宸茬敵璇峰姞鍏ャ€?{a.title}銆嶏紝绛夊緟闃熼暱纭`)}});
$('#detailContent').addEventListener('click',e=>{let id=+e.target.dataset.check;if(id){checked=checked.includes(id)?checked:[...checked,id];localStorage.setItem('weekend-checkins',JSON.stringify(checked));$('#detailDialog').close();render();toast('鎵撳崱鎴愬姛锛佸懆鏈鍦ㄥ彂鍏?鉁?)}if(e.target.dataset.share){const a=activities.find(x=>x.id===+e.target.dataset.share),text=`鍛ㄦ湯涓€璧峰幓锛?{a.title}锛?{a.time}锛?{a.price?'楼'+a.price:'鍏嶈垂'}銆傛潵鑷€屽懆鏈煄甯傛帰绱㈡寚鍗椼€峘;navigator.share?navigator.share({title:a.title,text}):navigator.clipboard.writeText(text).then(()=>toast('鎺ㄨ崘鏂囨宸插鍒讹紝鍙戠粰鏈嬪弸鍚?))}});
$('#interestChips').addEventListener('click',e=>{if(!e.target.matches('.chip'))return;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');selected=e.target.dataset.interest;render()});
['#budget','#people'].forEach(s=>$(s).addEventListener('change',render));function toggleWeather(){weather=weather==='sunny'?'rainy':'sunny';document.querySelector('.weather-card').innerHTML=weather==='sunny'?'<span class="weather-icon">鈽€</span><div><b>鏅存湕锛?4掳C</b><small>寰 路 閫傚悎鎴峰鎺㈢储</small></div><button id="weatherToggle">鍒囨崲</button>':'<span class="weather-icon">鈽?/span><div><b>灏忛洦锛?8掳C</b><small>娼箍 路 浼樺厛瀹ゅ唴娲诲姩</small></div><button id="weatherToggle">鍒囨崲</button>';$('#weatherToggle').onclick=toggleWeather;render()}$('#weatherToggle').onclick=toggleWeather;
$('#locateBtn').onclick=()=>toast('宸叉寜浣犻檮杩?3km 閲嶆柊鎺掑簭');$('#startTeam').onclick=()=>$('#teamDialog').showModal();$('#publishTeam').onclick=()=>{$('#teamDialog').close();toast('缁勯槦宸插彂甯冿紝姝ｅ湪涓轰綘瀵绘壘鍚屼即')};document.querySelectorAll('.close').forEach(x=>x.onclick=()=>x.closest('dialog').close());render();

