const $=(s)=>document.querySelector(s);
const activities=[
 {id:1,title:'西岸艺术季 · 夜场',type:'展览',price:60,time:'今天 18:30',district:'徐汇滨江',lat:31.183,lng:121.448,icon:'▣',team:'还差 2 人',tag:'室内外'},
 {id:2,title:'大学路周末创意市集',type:'市集',price:0,time:'今天 14:00',district:'五角场',lat:31.301,lng:121.513,icon:'✦',team:'已有 3 人',tag:'免费'},
 {id:3,title:'屋顶爵士 · 日落场',type:'演出',price:128,time:'今天 19:30',district:'静安寺',lat:31.227,lng:121.444,icon:'♫',team:'还差 1 人',tag:'日落限定'},
 {id:4,title:'佘山轻徒步 · 森林线',type:'徒步',price:45,time:'明天 08:00',district:'佘山',lat:31.097,lng:121.191,icon:'⌁',team:'已有 5 人',tag:'自然'}
];
const routes=[
 {id:'r1',title:'西岸日落漫游',meta:'¥68 · 2.5h · 2.1km',copy:'展览 → 江边散步 → 爵士日落场',tone:'coral',people:'1 位同校搭子正在等你'},
 {id:'r2',title:'大学路慢逛计划',meta:'免费 · 1.5h · 1.4km',copy:'创意市集 → 独立书店 → 深夜食堂',tone:'lime',people:'适合一个人，也适合临时组队'},
 {id:'r3',title:'雨天艺术避难所',meta:'¥45 · 室内 · 今天可去',copy:'美术馆 → 咖啡 → 黑胶试听室',tone:'blue',people:'天气变化时自动成为首选'}
];
let view='home', map, selectedType='全部', saved=JSON.parse(localStorage.getItem('weekend-saved')||'[]');
let user=JSON.parse(localStorage.getItem('weekend-user')||'null');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function header(){return `<header class="topbar"><button class="brand" data-nav="home"><i>W</i> WEEKEND</button><nav>${[['home','首页'],['map','地图探索'],['groups','出发局'],['community','社区攻略']].map(([id,n])=>`<button data-nav="${id}" class="${view===id?'active':''}">${n}</button>`).join('')}</nav><div class="top-actions"><button class="icon-btn" data-action="search" aria-label="搜索">⌕</button><button class="icon-btn" data-action="messages" aria-label="消息">◌<span></span></button><button class="profile-btn" data-action="profile">${user?user.nickname.slice(0,1):'登录'}</button></div></header>`}
function mobileNav(){return `<nav class="mobile-nav">${[['home','⌂','首页'],['map','⌖','地图'],['groups','◎','出发'],['community','◈','社区'],['profile','◉','我的']].map(([id,i,n])=>`<button data-nav="${id}" class="${view===id?'active':''}"><b>${i}</b>${n}</button>`).join('')}</nav>`}
function routeCard(r){return `<article class="route-card ${r.tone}"><p>为你生成的路线</p><h3>${r.title}</h3><b>${r.meta}</b><span>${r.copy}</span><small>✦ ${r.people}</small><button data-route="${r.id}">查看路线 →</button></article>`}
function activityCard(a,compact=false){return `<article class="activity-card ${compact?'compact':''}"><div class="activity-symbol type-${a.type}">${a.icon}</div><div><p>${a.tag} · ${a.district}</p><h3>${a.title}</h3><span>${a.time}　${a.price?'¥'+a.price:'免费'}　${a.team}</span></div><button class="save ${saved.includes(a.id)?'saved':''}" data-save="${a.id}" aria-label="收藏">${saved.includes(a.id)?'♥':'♡'}</button><button class="card-link" data-activity="${a.id}">详情</button></article>`}
function home(){return `<main class="page home"><section class="home-hero"><div><p class="eyebrow">SHANGHAI · SAT 20 SEP · 24°C</p><h1>今天，<em>怎么过？</em></h1><p>按此刻的时间、天气和心情，找到一条真的能出发的城市路线。</p><div class="moods">${['一个人放空','¥50 内','约会但不俗套','想找搭子','下雨也能玩'].map(x=>`<button>${x}</button>`).join('')}</div></div><aside class="pulse"><p>城市脉搏</p><b><i></i> 18 个活动正在发生</b><span>徐汇滨江和静安寺最热闹</span><button data-nav="map">打开地图</button></aside></section><section class="section-head"><div><p class="eyebrow">START HERE</p><h2>三条可直接出发的路线</h2></div><button data-nav="map">查看全部 ↗</button></section><section class="routes">${routes.map(routeCard).join('')}</section><section class="nearby"><div class="section-head"><div><p class="eyebrow">STARTING SOON</p><h2>附近即将开始</h2></div><button data-nav="groups">找同行的人 →</button></div><div class="activity-grid">${activities.slice(0,3).map(a=>activityCard(a,true)).join('')}</div></section><section class="saved-strip"><div><p class="eyebrow">YOUR LIST</p><h2>想去的地方</h2><span>${saved.length?`你已保存 ${saved.length} 个地点`:'收藏一处地方，下次从这里出发。'}</span></div><button data-nav="profile">打开我的清单 →</button></section></main>`}
function mapView(){return `<main class="map-page"><aside class="map-list"><div class="map-search">⌕ <input placeholder="搜索活动、地点、街区" aria-label="搜索" /></div><div class="filter-row">${['全部','展览','市集','演出','徒步'].map(x=>`<button data-filter="${x}" class="${selectedType===x?'selected':''}">${x}</button>`).join('')}</div><div class="list-head"><b>${activities.filter(a=>selectedType==='全部'||a.type===selectedType).length} 个附近好去处</b><span>今天 · 3km 内</span></div><div id="mapCards">${activities.filter(a=>selectedType==='全部'||a.type===selectedType).map(a=>activityCard(a)).join('')}</div></aside><section class="map-stage"><div id="map"></div><div class="map-float"><b>上海 · 你在这里</b><span>拖动地图后可探索新区域</span></div><button class="search-area" id="searchArea">搜索此区域</button><div class="map-legend"><span>▣ 展览</span><span>✦ 市集</span><span>♫ 演出</span><span>◎ 出发局</span></div></section></main>`}
function groups(){const gs=[['西岸日落局','今天 17:50 · 西岸美术馆门口','2 / 4 人','社恐友好，慢慢逛，不赶行程。'],['佘山晨间轻徒步','明天 07:40 · 9 号线佘山站','5 / 6 人','全程 8km，新手可参加。'],['大学路市集搭子','今天 14:20 · 五角场地铁站','3 / 5 人','预算 ¥50 内，想逛就逛。']];return `<main class="page groups"><section class="page-title"><p class="eyebrow">FIND YOUR CREW</p><h1>这周末，<em>和谁出发？</em></h1><button class="primary" data-action="create-group">＋ 发起出发局</button></section><div class="group-tabs"><button class="active">即将出发</button><button>我已加入</button><button>我发起的</button></div><section class="group-grid">${gs.map((g,i)=>`<article class="group-card"><div class="group-art a${i}">◎</div><p>${g[1]}</p><h3>${g[0]}</h3><b>${g[2]}</b><span>${g[3]}</span><footer><div class="avatars">林　周　陈</div><button data-join="${i}">申请加入</button></footer></article>`).join('')}</section></main>`}
function community(){return `<main class="page community"><section class="page-title"><p class="eyebrow">CITY NOTES</p><h1>有人已经替你，<em>先走了一遍。</em></h1><button class="primary" data-action="publish">写一篇攻略</button></section><div class="community-layout"><aside><b>发现攻略</b><button class="active">本周热门</button><button>低预算路线</button><button>雨天备选</button><button>新生指南</button><button>独自探索</button></aside><section class="post-feed">${[['¥88 逛完西岸的一整个下午','美术馆的预约要提前；日落后沿江散步比想象中舒服。','徐汇滨江 · 2.5h · 24 人收藏'],['第一次一个人去大学路，反而很自在','这条路线不用预约，带 ¥50 就够。','五角场 · 1.5h · 16 人收藏'],['雨天也值得出门的三家小展','地铁都能到，适合临时改变计划。','静安 · 3h · 31 人收藏']].map((p,i)=>`<article class="post"><div class="post-cover c${i}"></div><div><p>林予安 · 2 小时前</p><h3>${p[0]}</h3><span>${p[1]}</span><footer>${p[2]}　　♡ ${12+i*9}　　◌ ${3+i}</footer></div></article>`).join('')}</section></div></main>`}
function profile(){if(!user)return `<main class="empty-page"><p class="eyebrow">YOUR CITY, YOUR WAY</p><h1>登录后，开始建立<br/><em>你的城市档案。</em></h1><p>收藏路线、记录足迹，和同校的人一起出发。</p><button class="primary" data-action="auth">用邮箱开始</button></main>`;return `<main class="page profile"><section class="profile-hero"><div class="big-avatar">${user.nickname.slice(0,1)}</div><div><p class="eyebrow">SHANGHAI EXPLORER</p><h1>${user.nickname}</h1><span>上海 · 展览雷达 · 周末慢游者</span><p>“把普通周末过得有点意思。”</p></div><button>编辑资料</button></section><section class="profile-stats"><div><b>12</b><span>探索地点</span></div><div><b>4</b><span>完成路线</span></div><div><b>${saved.length}</b><span>想去清单</span></div><div><b>2</b><span>出发局</span></div></section><section class="profile-columns"><div><p class="eyebrow">SAVED</p><h2>我的想去清单</h2>${saved.length?activities.filter(a=>saved.includes(a.id)).map(a=>activityCard(a,true)).join(''):'<p class="muted">还没有收藏。去地图探索里挑一个吧。</p>'}</div><div><p class="eyebrow">FOOTPRINTS</p><h2>本周城市足迹</h2><div class="footprint"><b>徐汇滨江</b><span>西岸艺术季 · 9 月 14 日</span><b>大学路</b><span>周末创意市集 · 9 月 7 日</span></div></div></section></main>`}
function render(){const views={home,map:mapView,groups,community,profile};$('#app').innerHTML=header()+views[view]()+mobileNav();document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render();if(view==='map')setTimeout(initMap,0)});bindActions();if(view==='map')setTimeout(initMap,0)}
function initMap(){if(map){map.remove();map=null}map=L.map('map',{zoomControl:false}).setView([31.226,121.474],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);activities.filter(a=>selectedType==='全部'||a.type===selectedType).forEach(a=>{const marker=L.marker([a.lat,a.lng],{icon:L.divIcon({className:'weekend-marker',html:`<span class="type-${a.type}">${a.icon}</span>`})}).addTo(map);marker.bindPopup(`<b>${a.title}</b><br>${a.time} · ${a.price?'¥'+a.price:'免费'}<br><button class="popup-btn" onclick="document.dispatchEvent(new CustomEvent('openActivity',{detail:${a.id}}))">查看详情</button>`)});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{selectedType=b.dataset.filter;render()});$('#searchArea').onclick=()=>toast('已更新这一区域的活动');}
function bindActions(){document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{let id=+b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('weekend-saved',JSON.stringify(saved));render();toast(saved.includes(id)?'已加入想去清单':'已移出想去清单')});document.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>openActivity(+b.dataset.activity));document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>openRoute(b.dataset.route));document.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>requireLogin('申请加入出发局'));document.querySelectorAll('[data-action]').forEach(b=>{if(b.dataset.action==='auth'||b.dataset.action==='profile')b.onclick=()=>user?(view='profile',render()):openAuth('signup');if(b.dataset.action==='messages')b.onclick=openMessages;if(b.dataset.action==='create-group')b.onclick=()=>requireLogin('发起出发局');if(b.dataset.action==='publish')b.onclick=()=>requireLogin('发布攻略');if(b.dataset.action==='search')b.onclick=()=>{view='map';render()}})}
function openActivity(id){const a=activities.find(x=>x.id===id);$('#detailDialog').innerHTML=`<button class="close" data-close>×</button><div class="detail-head type-${a.type}">${a.icon}</div><div class="dialog-inner"><p class="eyebrow">${a.type} · ${a.district}</p><h2>${a.title}</h2><p class="detail-copy">${a.time} · ${a.price?'¥'+a.price:'免费'} · ${a.team}<br>适合晴朗傍晚出发；可从地图查看附近的路线与出发局。</p><button class="primary" data-detail-join>申请加入出发局</button></div>`;$('#detailDialog').showModal();$('[data-close]').onclick=()=>$('#detailDialog').close();$('[data-detail-join]').onclick=()=>{ $('#detailDialog').close();requireLogin('申请加入出发局') }}
function openRoute(id){const r=routes.find(x=>x.id===id);$('#detailDialog').innerHTML=`<button class="close" data-close>×</button><div class="dialog-inner"><p class="eyebrow">WEEKEND ROUTE</p><h2>${r.title}</h2><p class="detail-copy">${r.meta}<br>${r.copy}</p><ol class="route-steps"><li>14:30　集合 / 第一站</li><li>15:20　慢慢逛，不赶时间</li><li>17:45　日落前抵达最后一站</li></ol><button class="primary" data-detail-join>加入这条路线</button></div>`;$('#detailDialog').showModal();$('[data-close]').onclick=()=>$('#detailDialog').close();$('[data-detail-join]').onclick=()=>{ $('#detailDialog').close();requireLogin('加入路线') }}
function openAuth(mode){let step=mode;function paint(){const content=step==='signup'?`<p class="eyebrow">WELCOME TO WEEKEND</p><h2>开始你的城市档案</h2><p>用邮箱注册，收藏路线并和同校的人一起出发。</p><label>邮箱<input id="email" type="email" placeholder="name@example.com"></label><button class="primary" id="sendCode">发送验证码</button><small>已有账号？<button class="inline" id="goLogin">登录</button></small>`:step==='verify'?`<p class="eyebrow">CHECK YOUR INBOX</p><h2>输入 6 位验证码</h2><p>演示环境中可输入任意 6 位数字。</p><label>验证码<input id="code" inputmode="numeric" maxlength="6" placeholder="000000"></label><label>昵称<input id="nickname" placeholder="例如：林予安"></label><button class="primary" id="verifyCode">完成注册</button>`:step==='login'?`<p class="eyebrow">WELCOME BACK</p><h2>登录 WEEKEND</h2><label>邮箱<input type="email" placeholder="name@example.com"></label><label>密码<input type="password" placeholder="输入密码"></label><button class="primary" id="loginBtn">登录</button><small><button class="inline" id="forgot">忘记密码？</button>　<button class="inline" id="goSignup">注册账号</button></small>`:`<p class="eyebrow">RESET PASSWORD</p><h2>重置密码</h2><p>输入注册邮箱，我们会发送一个验证码。</p><label>邮箱<input type="email" placeholder="name@example.com"></label><button class="primary" id="backLogin">发送重置验证码</button>`;$('#authDialog').innerHTML=`<button class="close" data-close>×</button><div class="dialog-inner auth">${content}</div>`;$('#authDialog').showModal();$('[data-close]').onclick=()=>$('#authDialog').close();if($('#sendCode'))$('#sendCode').onclick=()=>{if(!$('#email').value)return toast('请输入邮箱');step='verify';paint()};if($('#verifyCode'))$('#verifyCode').onclick=()=>{if($('#code').value.length<6||!$('#nickname').value)return toast('请填写验证码和昵称');user={nickname:$('#nickname').value,email:'demo@example.com'};localStorage.setItem('weekend-user',JSON.stringify(user));$('#authDialog').close();render();toast('欢迎加入 WEEKEND')};if($('#loginBtn'))$('#loginBtn').onclick=()=>{user={nickname:'林予安',email:'demo@example.com'};localStorage.setItem('weekend-user',JSON.stringify(user));$('#authDialog').close();render();toast('登录成功')};if($('#goLogin'))$('#goLogin').onclick=()=>{step='login';paint()};if($('#goSignup'))$('#goSignup').onclick=()=>{step='signup';paint()};if($('#forgot'))$('#forgot').onclick=()=>{step='forgot';paint()};if($('#backLogin'))$('#backLogin').onclick=()=>{step='verify';paint()}}paint()}
function requireLogin(action){if(!user){toast(`登录后即可${action}`);openAuth('signup')}else toast(`已提交${action}申请，等待队长确认`)}
function openMessages(){$('#messageDialog').innerHTML=`<button class="close" data-close>×</button><div class="dialog-inner"><p class="eyebrow">INBOX</p><h2>消息</h2><div class="message-item"><b>西岸日落局</b><span>你的加入申请已被队长看到。</span><small>刚刚</small></div><div class="message-item"><b>WEEKEND 提醒</b><span>屋顶爵士将在 2 小时后开始。</span><small>12 分钟前</small></div></div>`;$('#messageDialog').showModal();$('[data-close]').onclick=()=>$('#messageDialog').close()}
document.addEventListener('openActivity',e=>openActivity(e.detail));render();
