const activities=[
 {id:1,title:'西岸艺术季 · 夜场',tag:'艺术 · 室内外',price:60,distance:'2.1km',time:'今天 18:30',people:'还差 2 人',interest:'艺术',outdoor:false,cls:'card-1',reason:'晴天傍晚，适合慢慢逛'},
 {id:2,title:'大学路周末创意市集',tag:'市集 · 逛吃',price:0,distance:'1.4km',time:'今天 14:00',people:'已有 3 人',interest:'市集',outdoor:true,cls:'card-2',reason:'免费且离你很近'},
 {id:3,title:'屋顶爵士 · 日落场',tag:'音乐 · 现场',price:128,distance:'3.2km',time:'今天 19:30',people:'还差 1 人',interest:'音乐',outdoor:true,cls:'card-3',reason:'晴朗天气的限定浪漫'},
 {id:4,title:'佘山轻徒步 · 森林线',tag:'自然 · 徒步',price:45,distance:'28km',time:'明天 08:00',people:'已有 5 人',interest:'自然',outdoor:true,cls:'card-4',reason:'体力刚好，风景正好'}
];
let selected='all', weather='sunny', saved=JSON.parse(localStorage.getItem('weekend-saved')||'[]'), checked=JSON.parse(localStorage.getItem('weekend-checkins')||'[]');
const $=s=>document.querySelector(s), list=$('#activityList');
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function render(){const budget=+$('#budget').value;let items=activities.filter(a=>(selected==='all'||a.interest===selected)&&a.price<=budget);if(weather==='rainy')items.sort((a,b)=>(a.outdoor?1:0)-(b.outdoor?1:0));$('#resultCount').textContent=items.length;list.innerHTML=items.length?items.map(a=>`<article class="card ${a.cls}"><button class="save ${saved.includes(a.id)?'saved':''}" data-save="${a.id}" aria-label="收藏 ${a.title}">${saved.includes(a.id)?'♥':'♡'}</button><span class="pill">${a.tag}</span><h3>${a.title}</h3><div class="meta"><span>¥${a.price||'免费'}</span><span>${a.distance}</span><span>${a.time}</span></div><p class="match">✦ ${weather==='rainy'&&a.outdoor?'雨天备选，建议带伞':a.reason}</p><div class="card-actions"><button class="detail" data-detail="${a.id}">查看详情</button><button class="join" data-join="${a.id}">组队 · ${a.people}</button></div></article>`).join(''):`<div class="empty">没有完全符合的活动。试试放宽预算或切换兴趣。</div>`;$('#savedCount').textContent=saved.length;$('#checkinCount').textContent=checked.length;$('#checkinCopy').textContent=checked.length?`这个周末已点亮 ${checked.length} 个新地点，继续保持。`:'从一个小小的周末计划开始。'}
document.addEventListener('click',e=>{const id=+(e.target.dataset.save||e.target.dataset.detail||e.target.dataset.join||0), a=activities.find(x=>x.id===id);if(e.target.dataset.save){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('weekend-saved',JSON.stringify(saved));render();toast(saved.includes(id)?'已加入你的周末清单':'已从清单移除')}if(e.target.dataset.detail&&a){$('#detailContent').innerHTML=`<div class="detail-art ${a.cls}"></div><p class="eyebrow">${a.tag}</p><h2>${a.title}</h2><p class="detail-line">${a.time} · 距离 ${a.distance} · ${a.price?'¥'+a.price:'免费'}<br>集合后自由探索，适合 ${$('#people').selectedOptions[0].textContent} 出发。</p><div class="detail-buttons"><button class="primary" data-check="${id}">${checked.includes(id)?'已完成打卡':'到场后打卡'}</button><button class="primary" data-share="${id}">分享攻略</button></div>`;$('#detailDialog').showModal()}if(e.target.dataset.join&&a){toast(`已申请加入「${a.title}」，等待队长确认`)}});
$('#detailContent').addEventListener('click',e=>{let id=+e.target.dataset.check;if(id){checked=checked.includes(id)?checked:[...checked,id];localStorage.setItem('weekend-checkins',JSON.stringify(checked));$('#detailDialog').close();render();toast('打卡成功！周末正在发光 ✦')}if(e.target.dataset.share){const a=activities.find(x=>x.id===+e.target.dataset.share),text=`周末一起去：${a.title}，${a.time}，${a.price?'¥'+a.price:'免费'}。来自「周末城市探索指南」`;navigator.share?navigator.share({title:a.title,text}):navigator.clipboard.writeText(text).then(()=>toast('推荐文案已复制，发给朋友吧'))}});
$('#interestChips').addEventListener('click',e=>{if(!e.target.matches('.chip'))return;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');selected=e.target.dataset.interest;render()});
['#budget','#people'].forEach(s=>$(s).addEventListener('change',render));function toggleWeather(){weather=weather==='sunny'?'rainy':'sunny';document.querySelector('.weather-card').innerHTML=weather==='sunny'?'<span class="weather-icon">☀</span><div><b>晴朗，24°C</b><small>微风 · 适合户外探索</small></div><button id="weatherToggle">切换</button>':'<span class="weather-icon">☂</span><div><b>小雨，18°C</b><small>潮湿 · 优先室内活动</small></div><button id="weatherToggle">切换</button>';$('#weatherToggle').onclick=toggleWeather;render()}$('#weatherToggle').onclick=toggleWeather;
$('#locateBtn').onclick=()=>toast('已按你附近 3km 重新排序');$('#startTeam').onclick=()=>$('#teamDialog').showModal();$('#publishTeam').onclick=()=>{$('#teamDialog').close();toast('组队已发布，正在为你寻找同伴')};document.querySelectorAll('.close').forEach(x=>x.onclick=()=>x.closest('dialog').close());render();
